#ifndef UOBJECT_ERROR_H
#define UOBJECT_ERROR_H

typedef enum uobj_error {
	UOBJ_OK,
	UOBJ_ERR_OUT_OF_MEMORY,
	UOBJ_ERR_NOT_REGISTERED,
	UOBJ_ERR_MODULUS_OUT_OF_RANGE,
	UOBJ_ERR_ELEMENT_EXISTED,
	UOBJ_ERR_NO_SUCH_ELEMENT,
	UOBJ_ERR_ELEMENT_EXISTS,
	UOBJ_ERR_INDEX_OUT_OF_BOUNDS
} uobj_error_t;

#endif /* UOBJECT_ERROR_H */
