#ifndef UOBJECT_TWEAKS_H
#define UOBJECT_TWEAKS_H

#define UOBJECT_HASHMAP_DEFAULT_MODULUS 73
#define UOBJECT_HASHSET_DEFAULT_MODULUS 73

#define UOBJECT_CONTEXT_INTERFACE_HASHTABLE_DEFAULT_MODULUS 199

#endif /* UOBJECT_TWEAKS_H */
